### ISSUE TITLE
Feedback not available in triggers

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-yamaha-rcp#23]
It does not appear that the available feedback options even show up in the triggers menus as an option.   Feedback seems to work fine on a regular button but just is not available to select under triggers.  Am I doing something wrong?  Thanks for this module and the work put into it!  It has helped our church tremendously!

**Comment by MeestorX** [comment]
Are triggers by feedback possible now (on any module)? Last time I checked that hadn’t been implemented.

**Comment by istnv** [comment]
@MeestorX The boolean feedbacks are listed as trigger sources and will trigger when 'true'

**Comment by MeestorX** [comment]
Ok, cool. 
I’ve already implemented the new feedback, didn’t realize they had already started supporting feedback triggers. I’ll have to update my build.
I now also have Rivage support in the build on my website.

**Comment by MeestorX** [comment]
Seems to be working. Let me know if you are still having issues with feedback triggers?

**Comment by obcocav** [comment]
@MeestorX .  Im running the latest beta and still don’t see the variables listed under the triggers feature.  Feedback works fine but variable themselves don’t see to show up.  Am I missing something?  Thanks!

**Comment by MeestorX** [comment]
There are no variables in my module. Your issue was about Feedback triggers, not variable triggers.

**Comment by MeestorX** [comment]
NM, looks like feedback triggers aren't working either. I'll look into that.

**Comment by MeestorX** [comment]
Correction. I just didn't know how to use them. They are working as expected. If you need assistance, please contact me at my website, https://discourse.checkcheckonetwo.com
